Update Jenkinsfile.txt

diff --git a/Jenkinsfile.txt b/Jenkinsfile.txt
--- a/Jenkinsfile.txt
+++ b/Jenkinsfile.txt
@@ -28,12 +28,34 @@ pipeline {
 		}
 		stage('Move build') {
             steps {
-				sh 'mv -f ./linux-x64 $DEPLOY_DIR'
+				sh 'mv -f ./linux-x64/* $DEPLOY_DIR'
 			}
 		}
 		stage('Restart Service') {
 			steps {
+				sh 'chmod 777 * $DEPLOY_DIR -R'
 				sh 'sudo systemctl restart $SERVICE'
+				sh 'sudo systemctl status $SERVICE'
+			}
+		}
+		stage('Get status Service') {
+			steps {
+				sh 'chmod 777 * $DEPLOY_DIR -R'
+				sh 'sudo systemctl restart $SERVICE'
+				
+				for i in 1 2 3 4 5; do
+					if sudo systemctl is-active --quiet $SERVICE; then
+						echo "✅ Service is active (running)"
+						exit 0
+					fi
+						echo "⏳ Waiting... ($i)"
+					sleep 2
+				done
+				
+				echo "❌ Service failed to start"
+					sudo systemctl status $SERVICE --no-pager
+					sudo journalctl -u $SERVICE --no-pager -n 20
+				exit 1
 			}
 		}
     }
